### ISSUE TITLE
lib/types.ml conflicts with compiler-libs' types

### ISSUE THREAD

**Issue by eras** [ryanrhymes/owl#1]
This has the effect that I cannot use it from my utop or ocaml top level:

    utop # #require "Owl";;
    The files /home/flux/ocaml/.opam/4.03.0+fp+flambda/lib/Owl/Owl.cma and
    /home/flux/ocaml/.opam/4.03.0+fp+flambda/lib/ocaml/compiler-libs/toploop.cmi
    disagree over interface Types

This is of course unfortunate that the collision can occur, but as long as OCaml doesn't have namespaces ;) it would be nice if Owl had all its modules prefixed with Owl_, possibly with an additional module Owl that has module aliases for the current names (module Owl = struct module Types = Owl_types etc). This would avoid introducing the module names that might conflict with other projects.

I can foresee that "utils" is also going to collide some projects..

I'm suggesting this instead of putting all inside the module Owl to avoid the binary size bloat that can occur with packing.

**Comment by ryanrhymes** [comment]
Thanks Eras. This is a very good suggestion. I have changed module names and now they start with owl_ . There is a new Owl model which provides aliases of these modules. Please have a try and I hope this solves the name conflict issue.
