### ISSUE TITLE
Printer output in utop (and ocaml-jupyter) is not flushed correctly

### ISSUE THREAD

**Issue by mseri** [ryanrhymes/owl#103]
I report from https://github.com/akabe/ocaml-jupyter/issues/50

> Matrix output
> This is clearly a bug of owl. The cause of this problem is that output buffer is not flushed. Try this:
```
# Owl.Mat.uniform 4 4 ;; flush stdout ;;
- : Owl.Mat.mat = 

         C0        C1       C2       C3
R0 0.108383  0.844251 0.727378 0.497851
R1 0.873218  0.243849 0.720696 0.544599
R2 0.838986 0.0246897 0.468628 0.625664
R3 0.614223  0.179304 0.772862 0.735753
```
> Although Owl's output is a little strange. OCaml-style pretty printing should use #install_printer like
> - https://github.com/akabe/slap/blob/master/lib/install_top.ml
> - https://github.com/mmottl/lacaml/blob/master/src/install_printers.ml

I didn’t have time to look into it yet, but seems reasonably easy to fix

**Comment by akabe** [comment]
Thanks for reporting the problem. I misunderstood a little. `#install_printer` is used at https://github.com/ryanrhymes/owl/blob/bd9e7c5828abc55fe2c6c78079b18da6434530c5/lib/owl_toplevel.ml#L22. I think unflushed output buffer causes this bug, and `#install_printer` is unrelaed.

**Comment by dbuenzli** [comment]
That's not the problem, it's not the duty of pretty printerto flush the formatter.

The problem may be that `owl`'s toplevel pretty-printing functions don't seem to use the pretty print argument but output directly using `Format.printf` (rather than `Format.fprintf`). See https://github.com/ryanrhymes/owl/blob/6ade63a61a850ab52839113d685274986079b9e0/lib/owl_dense_common.ml#L384-L390

**Comment by akabe** [comment]
Use `Format.printf "%a@."` instead of `"%a\n"`? `@.` prints `\n` and flushes the output buffer.

**Comment by dbuenzli** [comment]
> Use Format.printf "%a@." instead of "%a\n"?

No. As I said it's not the duty of pretty-printers to flush the buffer. (Aside it should not even use newlines as this generally derails the pretty-printing engine, at most `@\n`, but I'm not even sure a new line is needed here). 

When you install a pretty printer for a type `t` you install a function of type `Format.formatter -> t -> unit`. Now your pretty printer is supposed to print on the `Format.formatter` argument. `owl` does not.

**Comment by akabe** [comment]
I see. You say that, for example, a value of `mat list` should be shown like:

```
[ <contents of mat>;
  <contents of mat>;
  ... ]
```

but flushing the buffer disturbs the formatting such as indentation and placement of characters, don't you?

**Comment by dbuenzli** [comment]
Yes flushing/newlines etc. see the practical advices on [this page](https://ocaml.org/learn/tutorials/format.html). 

But again the problem here is not about flushing. In the jupyter report the matrix gets printed before the toplevel response and this is a sign they might not be using the same formatter, and this might well be the case because owl's formatter are not using the pretty-printer they are given as argument.

**Comment by ryanrhymes** [comment]
I have redesigned the pretty printing module completely. The new module should have solved the aforementioned issues. Even better, now the ndarray and matrix share a more consistent looking with new pretty printing function.

@akabe @mseri Could you please give it a try on notebook to see if this solves the problem? If so, we can move to solve the image loading issue?

**Comment by akabe** [comment]
I tried the current master branch by `opam pin add -y owl .`. The format bug is solved, but maybe I found some other bugs :cry:

- `install_printer` was not called. I manually called `#install_printer Owl.Dense.Matrix.Generic.pp_dsmat` and got the correct output.
- Does Owl newly depend on lapacke? If so, `conf-lapacke` should be needed in `opam` file, and `src/owl/jbuild` requires `-llapacke` library flag.

Do anyone see the above problems?

**Comment by ryanrhymes** [comment]
> `install_printer` was not called. I manually called `#install_printer Owl.Dense.Matrix.Generic.pp_dsmat` and got the correct output.

This is because toplevel is now included in `zoo` system. You need to load `owl_zoo` to install printers. I think `opam pin` only installs `owl` library. I still haven't figured out how to install both at the same time.

> - Does Owl newly depend on lapacke? If so, `conf-lapacke` should be needed in `opam` file, and `src/owl/jbuild` requires `-llapacke` library flag.

Yes, Owl has its own full interface to cblas and lapacke. I suppose people would install OpenBLAS which includes both cblas and lapacke. I did submit one conf-openblas to opam, but conf-openblas is not very well test, please give it a try, thanks.

**Comment by akabe** [comment]
@ryanrhymes Thanks. If so, the format bug is solved.

**Comment by mseri** [comment]
@ryanrhymes awesome!!

Concerning the pretty printers: when doing `#require "owl_zoo"` I get
```
Exception:
Invalid_argument
 "The ocamltoplevel.cma library from compiler-libs cannot be loaded inside the OCaml toplevel".
```
However the pretty printer works without issue and I do not need to do anything aside requiring `owl_zoo`.

Concerning the build, I incur in an issue similar to @akabe ones. It did not build until I added `-llapacke -lm`. I needed both to have it working, otherwise the linker complaints about missing lapacke symbols or missing `_ZGVbN4v___expf_finite`-like symbols:

```diff
diff --git a/src/owl/jbuild b/src/owl/jbuild
index d9ed4e8..f391e05 100644
--- a/src/owl/jbuild
+++ b/src/owl/jbuild
@@ -19,6 +19,8 @@
     -L/usr/local/lib/gcc/7
     -lopenblas
     -lgfortran
+    -llapacke
+    -lm
   ))
   (flags (:standard))
   (libraries (
```

**Comment by ryanrhymes** [comment]
I am a bit curious because if you have fortran compiler installed on your computer, openblas should already include lapacke. @mseri how did you install openblas? binary or compiled from source?

**Comment by mseri** [comment]
I had installed like bopenblas-dev and liblapacke-dev using apt lwast week at ICFP

**Comment by ryanrhymes** [comment]
OK, I see. I did that before, but later I realised if I compile from the openblas source directly, it already includes lapacke. Interestingly the performance is way better better than installing from the binary.

You can check the performance with `Linalg.Generic.peakflops ();;`

**Comment by mars0i** [comment]
I just want to point out that this 

> Concerning the build, I incur in an issue similar to @akabe ones. It did not build until I added -llapacke -lm. I needed both to have it working, otherwise the linker complaints about missing lapacke symbols or missing _ZGVbN4v___expf_finite-like symbols:

seems to be related to #61.  Maybe that was obvious--or obviously irrelevant.  I don't know much about either issue, but thought it wouldn't hurt to point it out.

**Comment by ryanrhymes** [comment]
This has also been addressed thanks to the new pretty printing module, I think, so closing it. About loading images to notebook, I think it is worth opening another separate issue.
