### ISSUE TITLE
linking error

### ISSUE THREAD

**Issue by mars0i** [ryanrhymes/owl#112]
With the current version of Owl, I'm getting the following errors when I try to compile native code executables.  I have no problem compiling bytecode and loading it into utop.  I don't think  have changed anything  relevant to the executable files.  I think it started happening after gettng the latest version of the master branch about 24 hours ago.  Any ideas about what might be causing this, or what I should check?  At the moment I'm not running the executables or designing new executables, so it's not urgent for me.  Thanks.
```
Undefined symbols for architecture x86_64:
  "_char_copy_impl", referenced from:
      _camlOwl_dense_common___owl_copy_inner_2123 in owl.a(owl_dense_common.o)
      _camlOwl_dense_common__string_4213 in owl.a(owl_dense_common.o)
  "_int16_copy_impl", referenced from:
      _camlOwl_dense_common___owl_copy_inner_2123 in owl.a(owl_dense_common.o)
      _camlOwl_dense_common__string_4213 in owl.a(owl_dense_common.o)
  "_int32_copy_impl", referenced from:
      _camlOwl_dense_common___owl_copy_inner_2123 in owl.a(owl_dense_common.o)
      _camlOwl_dense_common__string_4213 in owl.a(owl_dense_common.o)
  "_int64_copy_impl", referenced from:
      _camlOwl_dense_common___owl_copy_inner_2123 in owl.a(owl_dense_common.o)
      _camlOwl_dense_common__string_4213 in owl.a(owl_dense_common.o)
  "_int8_copy_impl", referenced from:
      _camlOwl_dense_common___owl_copy_inner_2123 in owl.a(owl_dense_common.o)
      _camlOwl_dense_common__string_4213 in owl.a(owl_dense_common.o)
  "_uint16_copy_impl", referenced from:
      _camlOwl_dense_common___owl_copy_inner_2123 in owl.a(owl_dense_common.o)
      _camlOwl_dense_common__string_4213 in owl.a(owl_dense_common.o)
  "_uint8_copy_impl", referenced from:
      _camlOwl_dense_common___owl_copy_inner_2123 in owl.a(owl_dense_common.o)
      _camlOwl_dense_common__string_4213 in owl.a(owl_dense_common.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "caml_startup", line 1:
Error: Error during linking
make: *** [all] Error 1
```
In case it's relevant, I use this `jbuild` file for the executables:
```
(jbuild_version 1)

(executables
 ((names (wrightfisherPDFs setchaintest))
	(public_names (wrightfisherPDFs setchaintest))
  (package models)
  (libraries (core models utils))
  (modes (native)) ; replace native with byte to make bytecode executable
 ;(ocamlopt_flags "-O3")
 ))
```
This is an example of a jbuild file for one of my library packages:
```
(jbuild_version 1)

(library 
 ((name        models)
  (public_name models)
  (modules (wrightfisher setchains tranmats credalsetPDF))
  (libraries (batteries core owl parmap utils))
  ;(ocamlopt_flags "-O3")
  ))
```

**Comment by jzstark** [comment]
@mars0i Thanks for finding this issue. I'm interested to try to reproduce the same issue on my machine, and it would be really helpful if you can provide a small example. Btw, I was thinking if it is possible that you have not cleaned up all the old version of `.a` files and link your code to them.

**Comment by ryanrhymes** [comment]
@mars0i Yes, there were typos relate to the functions added to owl_dense_common.c, which is currently being extended to integer types. Thanks for noticing this. Now it has been fixed, and please give it a try.

Thanks @jzstark for the help is fixing this 👍

**Comment by mars0i** [comment]
Yes, that fixed it for me.  Thanks Liang, @jzstark.
