### ISSUE TITLE
Strange interaction between plot functions

### ISSUE THREAD

**Issue by mars0i** [ryanrhymes/owl#113]
If I combine `plot` with `area`, the plotted area is incorrect if the `plot` line is on or near the displayed region, and `plot` is called before `area`.  I first noticed this kind of behavior with `draw_polygon` instead of `area`, but I did more testing with `area` since using it is a little bit simpler--there is only one defined edge.  I haven't experimented with other combinations involving `area` or `draw_polygon`.

Experiment 1:
```ocaml
module M = Owl.Mat;;
module P = Owl.Plot;;

let xs = M.sequential 1 10;;
let ys = M.map (fun x -> x**2.)  xs;;

(* An area plot: *)
let h = P.create "foo.pdf" in P.(area ~h xs ys; output h);;

(* Let's add line along the top edge: *)
let h = P.create "foo.pdf" in
P.(area ~h xs ys;
   plot ~h ~spec:[RGB(0,0,255); LineWidth 5.] xs ys;
   output h);;

(* Try the same thing but call plot for the line first: *)
let h = P.create "foo.pdf" in
P.(plot ~h ~spec:[RGB(0,0,255); LineWidth 5.] xs ys;
   area ~h xs ys;
   output h);;
(* Where did the blue line go? *)

(* Let's make the line wide.  First call area and then call plot. *)
let h = P.create "foo.pdf" in
P.(area ~h xs ys;
   plot ~h ~spec:[RGB(0,0,255); LineWidth 50.] xs ys;
   output h);;
(* It looks as if the line is centered along the edge of the area;
 * that makes sense. *)

(* Now lets try calling plot first: *)
let h = P.create "foo.pdf" in
P.(plot ~h ~spec:[RGB(0,0,255); LineWidth 50.] xs ys;
   area ~h xs ys;
   output h);;
(* Very strange.  It looks as if the plot line is missing, and the entire `area` region
 * has an extra wide edge on all sides, with some diagonal corners.  *)
```

Experiment 2:  Same as experiment 1, but for `plot`, give arguments `xs xs` rather than `xs ys`, so that a straight line is (supposed to be) drawn over the area.  With `plot` second, it behaves as expected.  With `plot` first, and `LineWidth 50.`, the image seems to be identical to the last example in experiment 1.

Experiment 3:
```ocaml
let ys' = M.map (fun x -> (x**2.) +. 10.)  xs;;
```
Now pass `xs ys` to `area`, and `xs ys'` to `plot`.  In this case, the line is blue even when `plot` is called first.  When `LineWidth` is 5.,  the image is as you would expect, whether `plot` is called first or second.  However, when `LineWidth` is called first, the `area` region again shows the distorted shape illustrated in experiments 1 and 2.

Here is the last image from experiment 3.  Notice the shape of the `area` region:
[foo.pdf](https://github.com/ryanrhymes/owl/files/1343075/foo.pdf)

**Comment by mars0i** [comment]
At least part of what's happening is that `LineWidth` in `plot` is affecting the width of the lines used for the fill pattern--i.e. what `FillPattern` specifies.  My guess is that there's an underlying pattern that's used to generate the solid fill for `FillPattern 0`, so a very thick line width ends up giving the `area` output a weird shape.

**Comment by mars0i** [comment]
I copied the two `line_width` lines from `plot` to `area`.  This allows `area` to override `plot`'s line width, but only when `LineWidth` is specified explicitly in `area`'s `~spec` value.  I don't understand this.  There's something I'm not seeing.

This is what I did.  The two lines containing `line_width` are new:
```ocaml
let area ?(h=_default_handle) ?(spec=[]) x y=
  let open Plplot in
  let x = Owl_dense_matrix.D.to_array x in
  let y = Owl_dense_matrix.D.to_array y in
  let xmin, xmax = Owl_stats.minmax x in
  let x = Array.(append (append [|xmin|] x) [|xmax|]) in
  let y = Array.(append (append [|0.|] y) [|0.|]) in
  _adjust_range h x X;
  _adjust_range h y Y;
  (* prepare the closure *)
  let p = h.pages.(h.current_page) in
  let color = _get_rgb spec p.fgcolor in
  let r, g, b = color in
  let line_style = _get_line_style spec 1 in
  let line_width = _get_line_width spec (-1.) in
  let fill_pattern = _get_fill_pattern spec 0 in
  (* drawing function *)
  let f = (fun () ->
    let r', g', b' = plgcol0 1 in
    plscol0 1 r g b;
    plcol0 1;
    if line_width > (-1.) then plwidth line_width;
    pllsty line_style;
    plline x y;
    plpsty fill_pattern;
    plfill x y;
    (* restore original settings *)
    plscol0 1 r' g' b';
    plcol0 1;
    pllsty 1
  )
  in
  (* add closure as a layer *)
  p.plots <- Array.append p.plots [|f|];
  (* add legend item to page *)
  _add_legend_item p BOX line_style color "" color fill_pattern color;
  if not h.holdon then output h
```

**Comment by mars0i** [comment]
The problem seems to be that the closure created in `plot` includes a `let` in the scope of an `if` test that is usually false.  As a result, all of the rest of the code in the closure doesn't get executed, including the code that restores settings to previous values.  Submitting a PR that fixes this, as well as a similar bug in `loglog`.

**Comment by ryanrhymes** [comment]
This is a great bug report, really appreciate that you managed to fix it. 👍
