### ISSUE TITLE
Not linking properly to FFI libs

### ISSUE THREAD

**Issue by hadils** [ryanrhymes/owl#115]
Here is my program:

`Hadil-Sabbaghs-MacBook-Pro:screenviz hadilsabbagh$ cat screenviz.ml
open Core
open Owl
open Neural.S
open Neural.S.Graph
open Algodiff.S

(* Labels
 * Dense.Ndarray.S of [|*, 22|]
 * The first 4 columns are cx, cy, w, h
 * The remaining 18 columns are the classifiers.
 *)

(* Jaccard function. Inputs are vectors [|cx, cy, w, h|] *)

let jaccard u v =
  let xa1 = u.(0) -. (u.(2) /. 2.) in
  let xa2 = u.(0) +. (u.(2) /. 2.) in
  let ya1 = u.(1) -. (u.(3) /. 2.) in
  let ya2 = u.(1) +. (u.(3) /. 2.) in
  let xb1 = v.(0) -. (v.(2) /. 2.) in
  let xb2 = v.(0) +. (v.(2) /. 2.) in
  let yb1 = v.(1) -. (v.(3) /. 2.) in
  let yb2 = v.(1) +. (v.(3) /. 2.) in
  let intersect_area = (Float.max 0. ((Float.min xa2 xb2) -. (Float.max xa1 xb1))) *. (Float.max 0. ((Float.min ya2 yb2) -. (Float.max ya1 yb1))) in
  intersect_area /. (u.(2) *. u.(3) +. v.(2) *. v.(3) -. intersect_area)

let jaccard_discr u v = if (jaccard u v < 0.5) then 0. else 1.

(* Loss function definition *)

(* partial VGG-16 network + extra layers *)

let make_network input_shape =
  input input_shape
  |> normalisation ~decay:0.9
  |> conv2d [|3;3;3;64|] [|1;1|] ~padding:VALID ~act_typ:Activation.Relu
  |> conv2d [|3;3;64;64|] [|1;1|] ~padding:VALID ~act_typ:Activation.Relu
  |> max_pool2d [|2;2|] [|2;2|] ~padding:VALID
  |> conv2d [|3;3;64;128|] [|1;1|] ~padding:VALID ~act_typ:Activation.Relu
  |> conv2d [|3;3;128;128|] [|1;1|] ~padding:VALID ~act_typ:Activation.Relu
  |> max_pool2d [|2;2|] [|2;2|] ~padding:VALID
  |> conv2d [|3;3;128;256|] [|1;1|] ~padding:VALID ~act_typ:Activation.Relu
  |> conv2d [|3;3;256;256|] [|1;1|] ~padding:VALID ~act_typ:Activation.Relu
  |> conv2d [|3;3;256;256|] [|1;1|] ~padding:VALID ~act_typ:Activation.Relu
  |> max_pool2d [|2;2|] [|2;2|] ~padding:VALID
  |> conv2d [|3;3;256;512|] [|1;1|] ~padding:VALID ~act_typ:Activation.Relu
  |> conv2d [|3;3;512;512|] [|1;1|] ~padding:VALID ~act_typ:Activation.Relu
  |> conv2d [|3;3;512;512|] [|1;1|] ~padding:VALID ~act_typ:Activation.Relu
  |> max_pool2d [|2;2|] [|2;2|] ~padding:VALID
  |> conv2d [|3;3;512;512|] [|1;1|] ~padding:VALID ~act_typ:Activation.Relu
  |> conv2d [|3;3;512;512|] [|1;1|] ~padding:VALID ~act_typ:Activation.Relu
  |> conv2d [|3;3;512;512|] [|1;1|] ~padding:VALID ~act_typ:Activation.Relu
  |> max_pool2d [|3;3|] [|1;1|] ~padding:VALID
  |> conv2d [|3;3;512;1024|] [|1;1|] ~padding:VALID ~act_typ:Activation.Relu
  |> conv2d [|1;1;1024;1024|] [|1;1|] ~padding:VALID ~act_typ:Activation.Relu
  |> conv2d [|1;1;1024;256|] [|1;1|]
  |> conv2d [|3;3;256;512|] [|2;2|] ~padding:VALID
  |> conv2d [|1;1;512;512|] [|1;1|]
  |> conv2d [|3;3;512;128|] [|1;1|]
  |> conv2d [|1;1;128;256|] [|2;2|] ~padding:VALID
  |> conv2d [|3;3;256;256|] [|1;1|]
  |> conv2d [|1;1;256;128|] [|1;1|]
  |> conv2d [|3;3;128;256|] [|1;1|]
  |> conv2d [|1;1;256;128|] [|1;1|]
  |> conv2d [|3;3;128;256|] [|1;1|]
  |> get_network`

Here is my jbuild file:

`Hadil-Sabbaghs-MacBook-Pro:screenviz hadilsabbagh$ cat jbuild
(jbuild_version 1)
(executable
  ((name screenviz)
  (libraries (owl core))
  (preprocess (pps (ppx_jane)))
  ))`

Here is the error that occurs when i run `jbuilder build screenviz.exe`:

`/root/.opam/4.05.0/lib/owl/owl.a(owl_dense_common.o): In function `camlOwl_dense_common___owl_copy_inner_5921':
/root/owl/_build/default/src/owl/owl_dense_common.ml:394: undefined reference to `int8_copy_impl'
/root/owl/_build/default/src/owl/owl_dense_common.ml:395: undefined reference to `uint8_copy_impl'
/root/owl/_build/default/src/owl/owl_dense_common.ml:396: undefined reference to `int16_copy_impl'
/root/owl/_build/default/src/owl/owl_dense_common.ml:397: undefined reference to `uint16_copy_impl'
/root/owl/_build/default/src/owl/owl_dense_common.ml:398: undefined reference to `int32_copy_impl'
/root/owl/_build/default/src/owl/owl_dense_common.ml:399: undefined reference to `int64_copy_impl'
/root/owl/_build/default/src/owl/owl_dense_common.ml:393: undefined reference to `char_copy_impl'
/root/.opam/4.05.0/lib/owl/owl.a(owl_dense_common.o): In function `camlOwl_dense_common__400':
:(.data+0x75a0): undefined reference to `int64_copy_impl'
:(.data+0x75a8): undefined reference to `int32_copy_impl'
:(.data+0x75b0): undefined reference to `uint16_copy_impl'
:(.data+0x75b8): undefined reference to `int16_copy_impl'
:(.data+0x75c0): undefined reference to `uint8_copy_impl'
:(.data+0x75c8): undefined reference to `int8_copy_impl'
:(.data+0x75d0): undefined reference to `char_copy_impl'
collect2: error: ld returned 1 exit status`

This occurs in Mac OS X 10.12 and also ubuntu 16.0 (using Docker).

**Comment by hadils** [comment]
This is using Ocaml 4.05.0

**Comment by hadils** [comment]
I used the latest build and found that the above problems are not present. I got the following error:
`File "_none_", line 1:
Error: Files screenviz.cmx and /root/.opam/4.05.0/lib/owl/owl.cmxa
       make inconsistent assumptions over implementation Owl_neural
`

I believe it is my code that is the problem.

**Comment by ryanrhymes** [comment]
@hadils thanks for reporting this, I think this is the same issue reported here: https://github.com/ryanrhymes/owl/issues/112 Yes, it has been solved :)

**Comment by ryanrhymes** [comment]
`File "_none_", line 1:
Error: Files screenviz.cmx and /root/.opam/4.05.0/lib/owl/owl.cmxa
       make inconsistent assumptions over implementation Owl_neural
`

For this latest issue, there can be two reasons imo: 1) the uninstallation wasn't complete so there might be some leftover files in .opam folder; 2) there can be some intermediate compiled files cached somewhere.

I myself sometimes encounter this problem, and it is usually solved by removing all the owl-related files then recompile.
