### ISSUE TITLE
sum functions sometimes return different values

### ISSUE THREAD

**Issue by mars0i** [ryanrhymes/owl#124]
`Mat.sum` and `Mat.sum_cols` don't always return the same value for the same sum, as the example below shows.  (It may take a couple of tries with `uniform` to get a difference between  `sum` and `sum_cols`.)  I'm assuming that the same is true for `sum_rows`.  The difference is small, of course, but maybe these should return the same value for the same sum?  Replacing one with the other should not change whether two numbers are strictly equal, I think.
```ocaml
# let m = Mat.((uniform 1 10) /$ 10.0);;
val m : (float, Bigarray.float64_elt) M.op_t2 =

          C0        C1        C2        C3        C4        C5        C6       C7        C8        C9
R0 0.0689677 0.0856961 0.0190419 0.0131349 0.0506694 0.0452381 0.0332929 0.087967 0.0271916 0.0981174

# (Mat.get (Mat.sum_cols m) 0 0) = (Mat.sum m);;
- : bool = false
# (Mat.get (Mat.sum_cols m) 0 0) -. (Mat.sum m);;
- : float = -1.11022302462515654e-16
```

**Comment by nilsbecker** [comment]
well it looks like you are calculating the same mathematical sum but in diferent order - it's expected that floating point arithmetic may give different answers within its accuracy, no?

**Comment by mars0i** [comment]
@nilsbecker, I think it would be ideal if the values were the same, so that if you switch from one method to another, nothing changes, but I understand your point and can accept that the values shouldn't have to be the same.  #125, which is related, might be more meaningful.

**Comment by ryanrhymes** [comment]
@mars0i I am glad that you actually noticed this 👍 In theory, you should be able to get the same result by calling `Mat.sum_rows x;;` and `Mat.sum ~axis:0 x;;`. 

However, there is some implementation details hidden behind the scene. `Mat.sum` calls the `sum` function in `Ndarray` which uses Owl's native implementation. But for `Mat.sum_rows` and `Mat.sum_cols`, I used matrix multiplication to accelerate the calculation. Comparing to `Mat.sum`, it can lead to over 100% performance improvement on my mac book.

The downside of using matrix multiplication is the returned result can be slightly different from the one returned by `sum`. I am still thinking whether to keep this implementation or simply replace it with native `sum` for consistency, by sacrificing some performance.

**Comment by ryanrhymes** [comment]
Note that the function `Mat.sum ~axis:0 x;;` I mentioned earlier has not been merged to the master branch at the moment. I will do that tomorrow.

**Comment by bluddy** [comment]
Ryan I noticed your compilation options can reduce precision. Might be a factor.

**Comment by mars0i** [comment]
> Comparing to Mat.sum, it can lead to over 100% performance improvement on my mac book.

In that case, I think it's probably worthwhile to live with the difference.

**Comment by ryanrhymes** [comment]
The sum functions have been unified so this issue should be solved already. Thanks again for reporting this.
