### ISSUE TITLE
Compilation error in owl_dense_common.ml

### ISSUE THREAD

**Issue by tpolakovic** [ryanrhymes/owl#128]
When trying to install owl, either from source or using opam (0.2.9 or dev), the installation fails with

`File "src/owl/owl_dense_common.ml", line 73, characters 31-52:
Error: This expression has type string but an expression was expected of type
         bytes`

OS is MacOS Sierra, OCaml 4.06.0, jbuilder 1.0+beta16. I'm not exactly sure, but it seems that this issue started with the update of OCaml.

**Comment by jzstark** [comment]
Indeed. According to the [Changelog](https://github.com/ocaml/ocaml/blob/4.06/Changes#L44), the default mode is now safe-string, which means `bytes` type cannot be used as mutable `string` by default.  For now I would suggest fall back to a lower (>= 4.04) OCaml version for Owl.

**Comment by ryanrhymes** [comment]
OK, this is due to the recent update in OCaml 4.06, which causes many opam packages fail to compile including Owl. It should be fixed and I will fix it these two days.

**Comment by ryanrhymes** [comment]
Actually, I just noticed David Scott's PR which already fixed this issue. It has been merged into Owl's master branch. Thanks @djs55 

https://github.com/ryanrhymes/owl/pull/130
