### ISSUE TITLE
Video for slides?

### ISSUE THREAD

**Issue by apatil** [ryanrhymes/owl#131]
Hi @ryanrhymes, is there video available for either of the slide decks in the readme?

**Comment by ryanrhymes** [comment]
Hi Anand, for tutorial I know for sure there is none. For ocaml workshop, I cannot remember if they recorded or not, but I think you can contact the workshop chair Gabriel Scherer @gasche and he can probably help :)

**Comment by gasche** [comment]
In theory there should be videos, but they have not been post-processed yet and I don't know when they will get out. You could follow [this Discuss thread](https://discuss.ocaml.org/t/ocaml-2017-videos/842) where they will be announced when available.

**Comment by ryanrhymes** [comment]
I think it is on Youtube now.
