### ISSUE TITLE
No such package: owl_top

### ISSUE THREAD

**Issue by macthecadillac** [ryanrhymes/owl#144]
Hi,

I'm still kind of new to OCaml so I don't know if this is genuinely a bug or just a rookie problem. Anyhow, when I added the line `#require "owl_top";;` to `.ocamlinit` as described in the instructions, utop gave me `No such package: owl_top`. I played around with the directive by changing it to `#require "owl";;` but then it gave me 
```
Cannot load required shared library dllowl_stubs.
Reason: /home/mac/.opam/4.06.0/lib/stublibs/dllowl_stubs.so: /home/mac/.opam/4.06.0/lib/stublibs/dllowl_stubs.so: undefined symbol: LAPACKE_dtpmqrt.
```
I installed owl through opam and installed all the external dependencies through `opam depext`. Here is my system info:
OS: Debian GNU/Linux 9.3
OCaml version: 4.06.0
Owl version: 0.3.0

Thanks

**Comment by mars0i** [comment]
Hi @macthecadillac-

This error
> Cannot load required shared library dllowl_stubs

is due to a known bug with the latest 1.x version of `opam`.  The solution is to upgrade to one of the opam 2.0 betas--at least beta4--and let it convert your .opam tree, or to move the file dllowl_stubs.so from ~/.opam/.../lib/stubslibs to ~/.opam/.../lib/stublibs.

I'm not sure if the `owl_top` error is related to this.

**Comment by macthecadillac** [comment]
I upgraded my opam to 2.0 beta 6 but it didn't seem to have changed anything. After that failed, I also tried reinstalling everything under ~/.opam from scratch but that again didn't fix anything.

**Comment by mars0i** [comment]
Ah, sorry for making you do all that work without a result.  You ran `eval $(opam env)`, right?  Oh, wait--I wasn't reading carefully.  I really did make you do work for nothing.  My mistake--sorry about that.  It looks you had dllowl_stubs.so in the right place.

This is not something I know much about, but I think it's a different error.  @ryanrhymes and others may have a better idea.

You could try installing with Docker instead if you want: https://github.com/ryanrhymes/owl#option-2-pull-from-docker-hub

**Comment by mars0i** [comment]
This may be related to #104 and #103.

**Comment by macthecadillac** [comment]
After a bit of trial and error, the suggestions in #103 worked. Thanks
