### ISSUE TITLE
Missing binomial functions

### ISSUE THREAD

**Issue by mars0i** [ryanrhymes/owl#160]
Binomial distribution functions were lost when GSL was removed, and need to be added back.

**Comment by ryanrhymes** [comment]
Binomial related functions have been added, please check [{this doc}](http://www.cl.cam.ac.uk/~lw525/owl/apidoc/owl_stats.html#discrete-random-variables).

**Comment by mars0i** [comment]
Thanks Liang.  (Owl's `binomial_pdf` is about 2X faster than GSL's on larger integers.)
