### ISSUE TITLE
Missing combination_float function

### ISSUE THREAD

**Issue by mars0i** [ryanrhymes/owl#164]
`Maths.combination n k` returns the combination for `ints` `n` and `k`.  This means that the function only works for about `n` <= 6,  because beyond that results exceed the max positive value for `int`.  It would be useful to have a `combination_float` with signature `float  -> float -> float` in order to handle larger arguments.  (We previously had a GSL-based version of this function.)

(btw my current use case is just to use `combination_float` to write my own temporary version of a `binomial` probability mass function, which will be fixed by issue #160.  In the long run I think it would be good to have `combination_float` even if we have binomial probability functions, though.)

**Comment by ryanrhymes** [comment]
I have added `permutation_float` and `combination_float` back, [ [check the doc here] ](http://www.cl.cam.ac.uk/~lw525/owl/apidoc/owl_maths.html#factorials). But I will leave this issue open until I have time to implement a more efficient function by table looking up.

**Comment by mars0i** [comment]
Great--thanks Liang.

**Comment by ryanrhymes** [comment]
Table looking up method has been added as a more efficient solution, so I close this issue.
