### ISSUE TITLE
Feature: Matrix exponential

### ISSUE THREAD

**Issue by tachukao** [ryanrhymes/owl#166]
It would be great to have an implementation of matrix exponential https://en.wikipedia.org/wiki/Matrix_exponential
like the `expm` in matlab and `scipy.linalg.expm` in python

**Comment by ryanrhymes** [comment]
This has been implemented, as well as `sinm`, `cosm` ... Please refer to [this doc](http://www.cl.cam.ac.uk/~lw525/owl/apidoc/owl_linalg_generic.html#matrix-functions) for details.
