### ISSUE TITLE
Mat.mapi, Mat.iteri function argument signature conflicts

### ISSUE THREAD

**Issue by mars0i** [ryanrhymes/owl#167]
It looks like some of the Matrix iteration functions have changed signatures. The function arguments of `mapi` and `iteri` formerly required two `int` index arguments, but now take only one `int` index.  The current definitions of these functions are `include`d from `Owl_dense_ndarray_generic`.  The ocamldocs for these functions still describe two-index function arguments, however. 

Is the signature change intentional?  If so, then the ocamldoc should change.  If not, then I think these functions should not be inherited from `owl_dense_ndarray_generic.ml`.

I vote for the old two-index versions.  Otherwise one has to map between 2D and 1D indexes, which is inconvenient and is more likely to lead to bugs, even using a standard helper function to perform the mapping.  (I would probably end up defining my own two-index functions in that case.)

**Comment by ryanrhymes** [comment]
Yes, that was done intentionally because passing 1d index is way faster than passing nd index, and also makes the interface of functor stack in Owl much simpler. 

However, I am not against having those iteration function of nd index. But I suggest giving them different names such as `iteri_nd` or `mapi_nd` ... do you think this makes sense? Let me know if you have better naming scheme.

The doc needs to be updated, thanks for pointing out. After migrating to sphinx, there are many places need to be fixed, my apologies.

**Comment by ryanrhymes** [comment]
Another reason for this is because after removing Vec module from Owl, we can use either ndarray or matrix module for vectors, allowing 1d index makes things easier when iterating elements in vectors.

**Comment by mars0i** [comment]
I see.  OK. 

By calling it `_nd` I am guessing that the idea is that it will work for 3D and 4D ndarrays as well as matrices.  Does that mean that the parameter for the function argument would be an array or list, so that the number of indexes would not be specified in the signature?

I'm thinking that it would also be worthwhile to have `mapi_2d` and `iteri_2d`, since matrices are so common.  Having a function argument with signature `int -> int -> float -> float` seems more convenient in many cases, rather than passing in a list or array, e.g. `int array -> float -> float`, and with a special 2D iteration function, the number of indexes on the function argument will be type checked.

**Comment by mars0i** [comment]
I see now that the ocamldoc for `Mat.init` mentions `Owl_utils.ind`--I think that's the function I was lookign for.  There is also `Mat.init_nd`, I see.  Why is it called `_nd`, though, if it always uses two indexes?  Why not `_2d`?

**Comment by ryanrhymes** [comment]
Yes, there are `i1d` and `ind` two functions in Owl to help you to translate between 1d and nd indices. You can search the doc to find the. 

The original reason of calling these iteration functions `*_nd` is to make sure that Matrix and Ndarray have consistent names, this makes writing signatures for functors easier, also make the signature file smaller.

As I said, I am definitely not against having them back, just need to figure out the right names, `*_2d` sounds reasonable to me. Owl has been undertaking some structural changes, so if you notice any changes that make it less good than before, please do fire an issue to notify me, I will try to sort it out. Many thanks.

**Comment by mars0i** [comment]
Thanks Liang.  I'm not necessarily against `*_nd` if there's a good reason.  Other things being equal I think that `*2d` is more intuitive in the matrix modules.

(Wow, LaTeX in the docs.  More in Slack.)  That's nice!  Can the API documentation still be run through `ocamldoc` and `odoc`?  The LaTeX won't be interpreted, I assume, but it's nice to be able to run `odig` and get a document tree for everything that's installed.)

**Comment by ryanrhymes** [comment]
The new iterations have been added, ndarray uses *_nd as suffix and matrix uses _2d. You can refer to [this doc](http://www.cl.cam.ac.uk/~lw525/owl/apidoc/owl_dense_matrix_generic.html#iteration-functions) for details.

However I haven't got enough time to add corresponding unit tests. In case you notice any bugs, please do fire an issue on github. Many thanks.
