### ISSUE TITLE
Missing element-wise exponentiation by a scalar.

### ISSUE THREAD

**Issue by jotterbach** [ryanrhymes/owl#171]
It would be great to have an operator like`$**` that does element-wise power by a scalar. E.g I want to do something like `Mat.(x $** 2.)` rather than `Mat.(x * x)` to create the element wise square of a matrix. Similarly `**$` can be used to element-wise exponentiation of the scalar to the power of the matrix entries.

**Comment by mars0i** [comment]
It might make more sense for the operator to be `**$` if the scalar will appear on the right side.  In other operator names, the `$` is on the side where the scalar appears.

**Comment by ryanrhymes** [comment]
OK, all including `**@` for matrix power have been added to Owl. Please refer to [this doc](http://www.cl.cam.ac.uk/~lw525/owl/apidoc/owl_operator.html#matrix-specific-operators) for details.
