### ISSUE TITLE
feature wish: more slicing

### ISSUE THREAD

**Issue by nilsbecker** [ryanrhymes/owl#18]
hi, it would be great to have the equivalent of numpy's  `array[3:10, 2: -4, ::2, ::-1]`. afaics so far we have only `array[:,3]`. 

extending the functionality would probably require a richer variant type for the slice indices than `int option`. something like `All | I of int | R of int * int | R' of int * int * int` where `R` and `R'` are ranges with increment 1 or with given increment, respectively, and `I` stands for a single index. About the negative indices: i think jane street uses those as well for arrays, may be worth checking that. 

it would be good to have some index that means `end`. but i think it's  too cumbersome to replace the `int`'s above by another variant `End | Interior of int`, because it requires typing `Interior` (or something shorter) all the time. so using `-1` for the end as in numpy or potentially `0` when dealing with fortran arrays seems better. (anyway, i guess in owl we always have c-layout, no?)

**Comment by ryanrhymes** [comment]
Hi @nilsbecker 

Thanks for the suggestion. Slicing will be certainly enhanced in future release. I am currently waiting for a couple of new features to be added in new OCaml 4.05 and 4.06 which will make indexing much easier. Anyway this has been added to my TODO list.

Yes, stick to one layout saves a lot of troubles. Owl only uses c-layout and starts indexing with 0. As far as I know, mixing them is a source of bugs, especially when you use Fortran style layout-out and indexing (start with 1) with other native OCaml data structures like array and list (start with 0).

**Comment by nilsbecker** [comment]
interesting: what will 4.05 and 4.06 bring?

**Comment by ryanrhymes** [comment]
This has been addressed in 0.2.3, please see my tutorial on new slicing function:  [Indexing and Slicing](https://github.com/ryanrhymes/owl/wiki/Tutorial:-Indexing-and-Slicing)
