### ISSUE TITLE
diff function

### ISSUE THREAD

**Issue by tachukao** [ryanrhymes/owl#194]
Is there a way of doing finite differences along an axis, like the `np.diff` function in `numpy` or `diff` function in matlab? Would be very helpful. Thank you!

**Comment by ryanrhymes** [comment]
I've added into both Ndarray and Matrix module, please refer to http://www.cl.cam.ac.uk/~lw525/owl/apidoc/owl_dense_ndarray_generic.html

Let me know in case there are bugs, thanks.
