### ISSUE TITLE
Question: eigenvalue problem

### ISSUE THREAD

**Issue by wkwkes** [ryanrhymes/owl#27]
Hi, I searched this repository for a function to the solve the eigenvalue problem, but could not find a suitable one.
Is there any way to solve it using Owl? If not, will Owl provide it in future? Or Do I miss somthing?

**Comment by ryanrhymes** [comment]
Hi @wkwkes 

you are right, there wasn't any yet, but it is very easy to add actually. I added four functions a moment ago and you can try them out if you are using docker image or build from master branch yourself.

The four functions in Linalg module are
```ocaml 
val eigen_symm : mat_d -> mat_d                       (* real symmetric, returns eigenvalues *)
val eigen_symmv : mat_d -> mat_d * mat_d       (* real symmetric, returns eigenvalues and vectors *)
val eigen_nonsymm : mat_d -> mat_z                 (* real asymmetric, returns eigenvalues *)
val eigen_nonsymmv : mat_d -> mat_z * mat_z  (* real symmetric, returns eigenvalues and vectors *)
```

Here is an example:

```ocaml 
let x = Mat.semidef 4;;
let v, z = Linalg.eigen_symmv x;;

let z' = Linalg.inv z;;
Mat.(z' $@ x $@ z);;
```

I hope this suits your need for the time being. The linalg module will be redesigned soon in the future to provide better apis :)

**Comment by wkwkes** [comment]
This is what I wanted.
Thank you for the so quick response!
