### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by smolkaj** [ryanrhymes/owl#35]
I just wanted to say thank you for this library, @ryanrhymes! 👍 🥇 👍 

It's amazing to see someone work on a numeric computation library for OCaml, and the [initial performance benchmarks](https://github.com/ryanrhymes/owl/wiki/Evaluation:-Performance-Test) look super promising!

**Comment by ryanrhymes** [comment]
Hi Steffen, thank you for trying out Owl. I am really happy to see more people playing with it, experimenting with it, and even hacking it :)  It is still in quite a prototype stage, so all comments and feedback are highly appreciate. Thanks.

I hope Owl can be a good choice in future for those want to build numerical and analytical applications in OCaml.
