### ISSUE TITLE
operator typos on tutorial page

### ISSUE THREAD

**Issue by mars0i** [ryanrhymes/owl#43]
I noticed minor typos on this page, https://github.com/ryanrhymes/owl/wiki/Tutorial:-Matrix-Manipulation.  It includes the following list:

```ocaml
Mat.(x +@ y);;    (* add two matrices *)
Mat.(x -@ y);;    (* subtract y from x *)
Mat.(x *@ y);;    (* element-wise multiplication *)
Mat.(x /@ y);;    (* element-wise division *)
Mat.(x $@ y);;    (* dot product of x and y *)
```

Element-wise multiplication should be `*` and the dot product should be `*@`.  This might just be left over from an earlier version.  (I'm not supposed to be able to propose edits to the wiki pages, right?  I didn't see an edit icon.)

**Comment by ryanrhymes** [comment]
@mars0i Yes, they are a bit outdated, many thanks for pointing it out. I will update it later. I don't know either if you can edit the wiki, I would hope so.

I will start writing another more comprehensive guide for Owl in this repository: [Owl Guild](https://github.com/ryanrhymes/owl_guide). Currently it is empty, but this guide will replace these tutorials in future. Then you should be able to create PR directly if you notice any typos or mistakes in the guide. There are too many functionality are not really covered in the tutorials at the moment. :)

**Comment by ryanrhymes** [comment]
fixed :)
