### ISSUE TITLE
feature request: sorting

### ISSUE THREAD

**Issue by nilsbecker** [ryanrhymes/owl#53]
I couldn't find sorting functions for matrices or vectors. it would be good to have 

- sorting for vectors with customizable compare function, with a standard default compare

- sorting for matrices by row or by column (i guess here a compare function acting on the row/column has to be given always as there is no standard way), 

- potentially also for Nd arrays where the sort dimension can be given and the compare function would take a slice over all non-sorted dimensions. this seems a little less standard

it might be that in-place versions are also needed? ideally both...

**Comment by ryanrhymes** [comment]
My apologies for the late response. There is a new function `sort` in both Matrix and Ndarray module which will sort the numbers from smallest to the biggest. For the `sort` in `Any` module, you can pass in your own compare function.
