### ISSUE TITLE
undefined symbol: _ZGVbN4v___expf_finite

### ISSUE THREAD

**Issue by pklehre** [ryanrhymes/owl#61]
I have problems using owl from the toplevel (also with utop). Both when compiling owl from source, and when installing via opam, I get the following error message:

```
# #require "owl";;
/home/pkl/.opam/4.04.0/lib/ocaml/str.cma: loaded
/home/pkl/.opam/4.04.0/lib/ocaml/unix.cma: loaded
/home/pkl/.opam/4.04.0/lib/ocaml/bigarray.cma: loaded
/home/pkl/.opam/4.04.0/lib/bytes: added to search path
/home/pkl/.opam/4.04.0/lib/integers: added to search path
/home/pkl/.opam/4.04.0/lib/integers/integers.cma: loaded
/home/pkl/.opam/4.04.0/lib/integers/integer_printers.cma: loaded
/home/pkl/.opam/4.04.0/lib/ctypes: added to search path
/home/pkl/.opam/4.04.0/lib/ctypes/ctypes.cma: loaded
/home/pkl/.opam/4.04.0/lib/ctypes/ctypes-top.cma: loaded
/home/pkl/.opam/4.04.0/lib/ctypes/cstubs.cma: loaded
/home/pkl/.opam/4.04.0/lib/plplot: added to search path
/home/pkl/.opam/4.04.0/lib/plplot/plplot.cma: loaded
/home/pkl/.opam/4.04.0/lib/dolog: added to search path
/home/pkl/.opam/4.04.0/lib/dolog/dolog.cma: loaded
/home/pkl/.opam/4.04.0/lib/eigen: added to search path
/home/pkl/.opam/4.04.0/lib/eigen/eigen.cma: loaded
/home/pkl/.opam/4.04.0/lib/gsl: added to search path
/home/pkl/.opam/4.04.0/lib/gsl/gsl.cma: loaded
/home/pkl/.opam/4.04.0/lib/owl: added to search path
/home/pkl/.opam/4.04.0/lib/owl/owl.cma: loaded
Cannot load required shared library dllowl_stubs.
Reason: /home/pkl/.opam/4.04.0/lib/stublibs/dllowl_stubs.so: /home/pkl/.opam/4.04.0/lib/stublibs/dllowl_stubs.so: undefined symbol: _ZGVbN4v___expf_finite.

```

**Comment by pklehre** [comment]
I am running Debian stretch on my machine:

Linux phi 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux

**Comment by ryanrhymes** [comment]
@pklehre thanks for reporting this. I will have a look into this issue later this week.

**Comment by pklehre** [comment]
I tried compiling openblas from source rather than using the Debian package, but I get the same error message.

Could it be related to glibc?

https://git.amper.me/open-source/glibc/commit/977a30801f61b7bbc27e8f185c1e7eb49675c60c?w=1#a8a3714871bdc09d9bfcd3e07b20f1dad7b041d7

**Comment by aj-yay** [comment]
I was also getting same error in OpenSuse and Debian distributions. However I am not sure if it is related to distribution.

I think problem seem to be that math lib is not being linked, so adding -lm to  CCLib+: fix this.

To test it clone fresh repo , edit _oasis file to add -lm and then run make oasis followed by make.

Hope this helps.

**Comment by pklehre** [comment]
Yes, thanks. I can now use owl from the toplevel.

**Comment by mseri** [comment]
Worked for me as well but on the master version, not on the opam version.

**Comment by pklehre** [comment]
With the switch from oasis to jbuilder, this bug seems to have reappeared. 
It can be fixed by adding -m to c_library_flags in src/owl/jbuild

**Comment by ryanrhymes** [comment]
Many thanks @pklehre for reporting this, I have fixed the issue.
