### ISSUE TITLE
julia benchmark uses non-constant global `shape`

### ISSUE THREAD

**Issue by StefanKarpinski** [ryanrhymes/owl#67]
Cool project! It's always nice to see more people doing good work in numericcal computing.

I noticed that the Julia benchmark code [here](https://gist.github.com/ryanrhymes/b8bf0d3df8e99d36896cc4a1ceefaefc) uses the non-constant global variable `shape` inside of functions, which is a [performance no-no](https://docs.julialang.org/en/stable/manual/performance-tips/). The simplest fix is to just change that line to `const shape = (10,1000,10000)` since it never changes.

It is also a bit unclear from the benchmark code whether the standard recommendation not timing the first invocation of functions to avoid timing JIT is followed – only the function definitions are included in the gist, not their invocation. For real-world code, this doesn't matter since for long-running or repeated computations (i.e. the ones whose speed one cares about), JIT is a negligible part of the time, but benchmarks tend to be short, so JIT ends up looking substantial.

**Comment by ryanrhymes** [comment]
@StefanKarpinski Thank you very much for pointing it out. Yes, you are absolutely right that the constant shape should be used in the benchmark, also that the first invocation is the most expensive one. In my previous experiments, I dropped the results from the first invocation, then kept calling the same function 10 times (at least) then reported the average results.

That evaluation was done quite a long time ago. After that, Owl has undertaken several significant upgrades (with many more functions added). In general, Owl and Julia can achieve similar performance, but I do acknowledge that Julia can be faster in several cases. I plan to make another post to update these results.

**Comment by ryanrhymes** [comment]
I am currently working on the new benchmark after a series significant changes being made to Owl. I will post the new results soon. Thanks again for pointing it out.
