### ISSUE TITLE
memory error in Plot.contour function

### ISSUE THREAD

**Issue by ryanrhymes** [ryanrhymes/owl#7]
Executing the following code a couple of times in `utop` may cause segmentation fault. I have not figured out the reason for this.

let x = Dense.linspace (-2.5) 2.5 100 in
let y = Dense.linspace (-2.5) 2.5 50 in
let u, v = Dense.meshup x y in
let z = Dense.(Maths.sin @@ ((u *_@ 2.) +@ (v *_@ 2.))) in
let h = Plot.create "" in
let _ = Plot.contour ~h u v z in
Plot.output h;;

**Comment by ryanrhymes** [comment]
It doesn't seem to be Owl's problem. Executing the official example from Plplot website in `utop` will also cause segmentation fault. The example code is here: http://plplot.sourceforge.net/examples.php?demo=09&lbind=Ocaml

**Comment by dbuenzli** [comment]
Do you have a backtrace ? Also do you also get the segfault in the regular toplevel `ocaml` ?

**Comment by ryanrhymes** [comment]
No, I just noticed this today but haven't looked into details. But I guess that is Plplot's issue since the official example I posted before also causes the same problem. I will try toplevel later ...

**Comment by ryanrhymes** [comment]
Solved :)
