### ISSUE TITLE
Plot.image is not correctly implemented

### ISSUE THREAD

**Issue by ryanrhymes** [ryanrhymes/owl#70]
@jzstark The `Plot.image` seems flawed. I used the MNIST dataset to print out some numbers for testing, the image seems flipped. A simple example you can test as follows:

```ocaml
let z0 = Mat.create 100 100 200. in
let z1 = Mat.zeros 100 100 in
let z = Mat.(z0 @|| z1) in
Plot.image z;;
```

The code should generate a figure (100 x 200) with left part is white and right part is black. However, the `image` function generates a flipped figure.

**Comment by jzstark** [comment]
@ryanrhymes sorry for not doing a thorough test. on it now.
