### ISSUE TITLE
Cannot find "owl_upload_gist.sh"

### ISSUE THREAD

**Issue by jzstark** [ryanrhymes/owl#80]
Thanks for the new "zoo" module. I was playing with it and following the tutorial. When I run the command `owl -upload myscript`, I got the error msg: `sh: 1: owl_upload_gist.sh: not found`.  In the source code, the only mention of `owl_upload_gist.sh` is in `upload_gist` from `owl_zoo.ml`, but it doesn't specify what is this shellscript or where to find it.  

I also run `owl -list` and it turned out that  `owl_list_gist.sh` is also not found. So I suspect that it might be because of some configuration problem of system path on my machine. I can confirm that these `owl_*_gist.sh` scripts are not in `/usr/local/bin` where the `owl` command locates.

Thanks for any help!

**Comment by ryanrhymes** [comment]
The original files are in the `owl/script` folder. After you run `make && make install`, they will be copied to your local `bin` folder, so `owl` command can find them because `bin` should be included in `PATH`.

If they are not in `/usr/local/bin/`, can you manually copy them to the bin folder for the time being? Then let me know if it works.

**Comment by jzstark** [comment]
Thanks a lot, it works good. I successfully upload and reuse the code as instructed in the tutorial.  

BTW, One thing I notice here is that when I run `./test.ml` (where I load and reuse code from gist) the results is right, while in `utop` running `#use "test.ml";;` shows an error `Unknown directive 'zoo'`.  Of course, this is definitely not a big problem for now.

**Comment by ryanrhymes** [comment]
In `utop`, you need to manually load `owl_zoo` library with
```ocaml
#require "owl_zoo";;
```
because `#zoo` directive is defined in `owl_zoo` library. It would be nice if you can figure out why your system didn't copy the files to bin folder :)

**Comment by jzstark** [comment]
Thanks! Again, now it works good in `utop`. I think it might also be helpful to others so just put this tip into the tutorial. 
Sure, I'll try to find what went wrong on my system.

**Comment by mseri** [comment]
I think this could be adapted to install the necessary scripts and binaries in the `opam` bin subfolder. This would be owl fully working when the repo is pinned
