### ISSUE TITLE
svd doc comment mismatch

### ISSUE THREAD

**Issue by mars0i** [ryanrhymes/owl#84]
The doc comment for `svd` says that in the default thin representation, `u` will be *m* x *n*, `s` is a row vector, and `vt` is *n* x *n*.   However, if the argument to `svd` has fewer rows than columns, `u` is *m* x *m* and `vt` is *m* x *n*.   This may be the intended behavior.  The current behavior seems to work in the definition of `pinv`; I've noticed no problem with the behavior of `pinv`.    (I know close to nothing about SVDs, and less about reduced SVDs.)  Example:
```OCaml
# Linalg.Generic.svd (Mat.sequential 2 4);;

          C0        C1
R0 -0.293704 -0.955896
R1 -0.955896  0.293704


        C0      C1
R0 11.7335 1.52457


          C0        C1         C2        C3
R0 -0.325868 -0.432367  -0.538865 -0.645363
R1  0.770591  0.336243 -0.0981053 -0.532453

- : (float, float64_elt) t * (float, float64_elt) t * (float, float64_elt) t = (, , )
```

(Also, is it possible that a knowledgeable person would read the doc comment as implying that `s` will be *m* x *n* when `thin = false`?   That's how I read it based on the Wikipedia definition of SVD, but I'm not familiar with SVD programming conventions.  I gather that simply returning the singular values from the full sigma matrix is common.)

**Comment by ryanrhymes** [comment]
Marshall, thanks for noticing this issue. I have revised the documentation based on your feedback. In case it is still ambiguous, please do let me know or feel free to PR. Using reduced SVD by default is based on consideration of performance and memory usage.

Yes, `thin` might be a bit unclear (copied from julia actually), I used to consider `reduced`. Returning only svd values seems to be a common practice to save memory. You can easily expand it into a matrix with `Mat.digm` function.

**Comment by mars0i** [comment]
Seems clear now--thanks Liang.
