### ISSUE TITLE
version constraints for dependencies

### ISSUE THREAD

**Issue by akabe** [ryanrhymes/owl#85]
I found lack of version constraints of dependencies in `opam` file. opam sometimes installs too old versions of them, and causes compilation errors. Could you add explicit and correct constraints to `opam` file?

## add `dolog {>= '3.0'}`

dolog 0.6 causes an type error:

```
# File "lib/nlp/owl_nlp_utils.ml", line 15, characters 11-32:
# Error: This expression has type string but an expression was expected of type
#          string Lazy.t = string lazy_t
```

## add `eigen {>= '0.0.3'}`

eigen 0.0.2 has no `Eigen.Utils` module:

```
# File "lib/owl_dense_common.ml", line 47, characters 21-46:
# Error: Unbound module Eigen.Utils
```

## remove `oasis setup` 

This is not a bug, but unnecessary: https://github.com/ryanrhymes/owl/blob/master/opam/opam#L18
`oasis setup` generates files for installation, e.g., `setup.ml`, `myocamlbuild.ml`. Installation only requires them, not `oasis setup`. It meaninglessly regenerates the files.

**Comment by ryanrhymes** [comment]
@akabe many thanks for pointing this out. You are right. I will fix them later.

**Comment by akabe** [comment]
Thanks, but is this line https://github.com/ryanrhymes/owl/blob/master/opam/opam#L9 unnecessary?
