### ISSUE TITLE
Typo in https://github.com/ryanrhymes/owl/blob/master/ACKNOWLEDGEMENT.md

### ISSUE THREAD

**Issue by moosotc** [ryanrhymes/owl#86]
Typo in https://github.com/ryanrhymes/owl/blob/master/ACKNOWLEDGEMENT.md

"The plot module is built on top of Hezekiah M. Carty's project: ocmal-plplot."
Should be ocaml-plplot

**Comment by ryanrhymes** [comment]
Thanks @moosotc , I have fixed it.
