### ISSUE TITLE
Rename clone to copy?

### ISSUE THREAD

**Issue by mars0i** [ryanrhymes/owl#88]
The function of `Owl.Mat.clone` is analogous to the function of `Array.copy` in the base library, Batteries, and Jane Street Core.  I was wondering, if Owl is still in the stage where breaking changes can be made, whether it would be better to rename `clone` to `copy` to match the `Array` function name.  I don't have an opinion about this; I just wanted to raise the question.  I'm familiar with the name "clone" from other languages, so I'm comfortable with it.

**Comment by ryanrhymes** [comment]
I agree with your suggestion. I think it is OK since Owl is still experimental and can undertake breaking (or even architectural) changes at the moment. I will think about it: either change the name or introduce an alias. Thanks again for the comment, always appreciated 👍

**Comment by ryanrhymes** [comment]
After collecting some feedback from others, I will change `clone` to `copy`, being consistent with other libraries also being consistent with Owl's own usage. The changes will be merged to master branch later.

Meanwhile, `copy_to` will be the function to copy from one ndarray/matrix to another. Thanks for the suggestion.

**Comment by ryanrhymes** [comment]
Now all the `clone` functions have been changed to `copy`, so close it. Thanks for the advice.
