### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by superbobry** [ryanrhymes/owl#9]
It seems owl only has examples at the moment. These are no doubt nice to have, but running and inspecting them manually after each change could be less effective than automated testing. 

Have you considered adding a layer of unit/property tests?

**Comment by ryanrhymes** [comment]
Definitely needed! Sergei, would you be able to create a pull request to start this? When there is a test framework, we can add more tests as the development proceeds.

**Comment by superbobry** [comment]
Do you have any preferences regarding the test framework? There're at least two: oUnit and kaputt (and more if we only consider property testing).

**Comment by ryanrhymes** [comment]
Kaputt might be the better option imo, very flexible.

**Comment by mor1** [comment]
FWIW the mirage libs mostly use alcotest by @samoht: <https://github.com/mirage/alcotest>
Seems to work for all their (unit test) cases.

**Comment by ryanrhymes** [comment]
> FWIW the mirage libs mostly use alcotest by @samoht: https://github.com/mirage/alcotest
Seems to work for all their (unit test) cases.

I chose to use Alcotest. It works fine, so I close this issue now.
