### ISSUE TITLE
Add support for integer data types

### ISSUE THREAD

**Issue by bluddy** [ryanrhymes/owl#94]
It would be nice to have additional support for integer data types, so we have vectorized operations on uint8, uint16, int32 etc. This would make Owl useful for more applications -- practically anywhere where vectorization is desired.

**Comment by bluddy** [comment]
Looks like support is there via ndarray_generic? Is that right?

**Comment by ryanrhymes** [comment]
Hi Yotam, it is possible to incorporate integer types without architectural changes. Yes, many matrix functions rely on ndarray_generic as you noticed, which further relies on [owl_dense_common.ml](https://github.com/ryanrhymes/owl/blob/master/lib/owl_dense_common.ml), which further calls the functions in [owl_dense_common_c.c](https://github.com/ryanrhymes/owl/blob/master/lib/owl_dense_common_c.c), which further utilises `owl_dense_common_vec_*` as templates.

If you want to give it a try, e.g., adding add/sub/mul/div for `int`, these file needs to be modified. I hope this information is helpful, but please do ask if there is anything unclear.

**Comment by ryanrhymes** [comment]
integer type was already supported in Owl some time ago (for many basic operations), but you need use Dense.Ndarray.Generic module directly so it may not be very obvious. I will consider to add a separate mli file in future.
