### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by bluddy** [ryanrhymes/owl#95]
https://github.com/ryanrhymes/owl/blob/40642a121af76622fd91a6b2fee2260061fc84d4/lib/owl_dense_ndarray_generic.ml#L378

Just curious about this add function (and all the vectorized functions in the vicinity). Why do we need to convert the ndarrays? Doesn't that get expensive?

Also, shouldn't a (+=) function be a lot cheaper?

**Comment by ryanrhymes** [comment]
Good catch. Those code need to be cleaned up. I haven't had time to add corresponding functions in [owl_dense_common_c.c](https://github.com/ryanrhymes/owl/blob/master/lib/owl_dense_common_c.c) and [owl_dense_common.ml](https://github.com/ryanrhymes/owl/blob/master/lib/owl_dense_common.ml). But this will be done soon. 

Also, conversion may allow me to use `axpy`, `scal`, and etc. in CBLAS which is faster. But for small ndarray and matrices, the benefit is marginal.

**Comment by bluddy** [comment]
Digging some more into the code, it looks like you're converting every ndarray to 1xn. What's the reason for this?
